package libmtp;
import libmtp.LibmtpLibrary.LIBMTP_datatype_t;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * A data structure to hold allowed ranges of values<br>
 * <i>native declaration : /usr/local/Cellar/libmtp/1.1.13/include/libmtp.h:491</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mtp")
public class LIBMTP_allowed_values_struct extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public byte u8max() {
		return this.io.getByteField(this, 0);
	}
	@Field(0) 
	public LIBMTP_allowed_values_struct u8max(byte u8max) {
		this.io.setByteField(this, 0, u8max);
		return this;
	}
	@Field(1) 
	public byte u8min() {
		return this.io.getByteField(this, 1);
	}
	@Field(1) 
	public LIBMTP_allowed_values_struct u8min(byte u8min) {
		this.io.setByteField(this, 1, u8min);
		return this;
	}
	@Field(2) 
	public byte u8step() {
		return this.io.getByteField(this, 2);
	}
	@Field(2) 
	public LIBMTP_allowed_values_struct u8step(byte u8step) {
		this.io.setByteField(this, 2, u8step);
		return this;
	}
	/** C type : uint8_t* */
	@Field(3) 
	public Pointer<Byte > u8vals() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : uint8_t* */
	@Field(3) 
	public LIBMTP_allowed_values_struct u8vals(Pointer<Byte > u8vals) {
		this.io.setPointerField(this, 3, u8vals);
		return this;
	}
	@Field(4) 
	public byte i8max() {
		return this.io.getByteField(this, 4);
	}
	@Field(4) 
	public LIBMTP_allowed_values_struct i8max(byte i8max) {
		this.io.setByteField(this, 4, i8max);
		return this;
	}
	@Field(5) 
	public byte i8min() {
		return this.io.getByteField(this, 5);
	}
	@Field(5) 
	public LIBMTP_allowed_values_struct i8min(byte i8min) {
		this.io.setByteField(this, 5, i8min);
		return this;
	}
	@Field(6) 
	public byte i8step() {
		return this.io.getByteField(this, 6);
	}
	@Field(6) 
	public LIBMTP_allowed_values_struct i8step(byte i8step) {
		this.io.setByteField(this, 6, i8step);
		return this;
	}
	/** C type : int8_t* */
	@Field(7) 
	public Pointer<Byte > i8vals() {
		return this.io.getPointerField(this, 7);
	}
	/** C type : int8_t* */
	@Field(7) 
	public LIBMTP_allowed_values_struct i8vals(Pointer<Byte > i8vals) {
		this.io.setPointerField(this, 7, i8vals);
		return this;
	}
	@Field(8) 
	public short u16max() {
		return this.io.getShortField(this, 8);
	}
	@Field(8) 
	public LIBMTP_allowed_values_struct u16max(short u16max) {
		this.io.setShortField(this, 8, u16max);
		return this;
	}
	@Field(9) 
	public short u16min() {
		return this.io.getShortField(this, 9);
	}
	@Field(9) 
	public LIBMTP_allowed_values_struct u16min(short u16min) {
		this.io.setShortField(this, 9, u16min);
		return this;
	}
	@Field(10) 
	public short u16step() {
		return this.io.getShortField(this, 10);
	}
	@Field(10) 
	public LIBMTP_allowed_values_struct u16step(short u16step) {
		this.io.setShortField(this, 10, u16step);
		return this;
	}
	/** C type : uint16_t* */
	@Field(11) 
	public Pointer<Short > u16vals() {
		return this.io.getPointerField(this, 11);
	}
	/** C type : uint16_t* */
	@Field(11) 
	public LIBMTP_allowed_values_struct u16vals(Pointer<Short > u16vals) {
		this.io.setPointerField(this, 11, u16vals);
		return this;
	}
	@Field(12) 
	public short i16max() {
		return this.io.getShortField(this, 12);
	}
	@Field(12) 
	public LIBMTP_allowed_values_struct i16max(short i16max) {
		this.io.setShortField(this, 12, i16max);
		return this;
	}
	@Field(13) 
	public short i16min() {
		return this.io.getShortField(this, 13);
	}
	@Field(13) 
	public LIBMTP_allowed_values_struct i16min(short i16min) {
		this.io.setShortField(this, 13, i16min);
		return this;
	}
	@Field(14) 
	public short i16step() {
		return this.io.getShortField(this, 14);
	}
	@Field(14) 
	public LIBMTP_allowed_values_struct i16step(short i16step) {
		this.io.setShortField(this, 14, i16step);
		return this;
	}
	/** C type : int16_t* */
	@Field(15) 
	public Pointer<Short > i16vals() {
		return this.io.getPointerField(this, 15);
	}
	/** C type : int16_t* */
	@Field(15) 
	public LIBMTP_allowed_values_struct i16vals(Pointer<Short > i16vals) {
		this.io.setPointerField(this, 15, i16vals);
		return this;
	}
	@Field(16) 
	public int u32max() {
		return this.io.getIntField(this, 16);
	}
	@Field(16) 
	public LIBMTP_allowed_values_struct u32max(int u32max) {
		this.io.setIntField(this, 16, u32max);
		return this;
	}
	@Field(17) 
	public int u32min() {
		return this.io.getIntField(this, 17);
	}
	@Field(17) 
	public LIBMTP_allowed_values_struct u32min(int u32min) {
		this.io.setIntField(this, 17, u32min);
		return this;
	}
	@Field(18) 
	public int u32step() {
		return this.io.getIntField(this, 18);
	}
	@Field(18) 
	public LIBMTP_allowed_values_struct u32step(int u32step) {
		this.io.setIntField(this, 18, u32step);
		return this;
	}
	/** C type : uint32_t* */
	@Field(19) 
	public Pointer<Integer > u32vals() {
		return this.io.getPointerField(this, 19);
	}
	/** C type : uint32_t* */
	@Field(19) 
	public LIBMTP_allowed_values_struct u32vals(Pointer<Integer > u32vals) {
		this.io.setPointerField(this, 19, u32vals);
		return this;
	}
	@Field(20) 
	public int i32max() {
		return this.io.getIntField(this, 20);
	}
	@Field(20) 
	public LIBMTP_allowed_values_struct i32max(int i32max) {
		this.io.setIntField(this, 20, i32max);
		return this;
	}
	@Field(21) 
	public int i32min() {
		return this.io.getIntField(this, 21);
	}
	@Field(21) 
	public LIBMTP_allowed_values_struct i32min(int i32min) {
		this.io.setIntField(this, 21, i32min);
		return this;
	}
	@Field(22) 
	public int i32step() {
		return this.io.getIntField(this, 22);
	}
	@Field(22) 
	public LIBMTP_allowed_values_struct i32step(int i32step) {
		this.io.setIntField(this, 22, i32step);
		return this;
	}
	/** C type : int32_t* */
	@Field(23) 
	public Pointer<Integer > i32vals() {
		return this.io.getPointerField(this, 23);
	}
	/** C type : int32_t* */
	@Field(23) 
	public LIBMTP_allowed_values_struct i32vals(Pointer<Integer > i32vals) {
		this.io.setPointerField(this, 23, i32vals);
		return this;
	}
	@Field(24) 
	public long u64max() {
		return this.io.getLongField(this, 24);
	}
	@Field(24) 
	public LIBMTP_allowed_values_struct u64max(long u64max) {
		this.io.setLongField(this, 24, u64max);
		return this;
	}
	@Field(25) 
	public long u64min() {
		return this.io.getLongField(this, 25);
	}
	@Field(25) 
	public LIBMTP_allowed_values_struct u64min(long u64min) {
		this.io.setLongField(this, 25, u64min);
		return this;
	}
	@Field(26) 
	public long u64step() {
		return this.io.getLongField(this, 26);
	}
	@Field(26) 
	public LIBMTP_allowed_values_struct u64step(long u64step) {
		this.io.setLongField(this, 26, u64step);
		return this;
	}
	/** C type : uint64_t* */
	@Field(27) 
	public Pointer<Long > u64vals() {
		return this.io.getPointerField(this, 27);
	}
	/** C type : uint64_t* */
	@Field(27) 
	public LIBMTP_allowed_values_struct u64vals(Pointer<Long > u64vals) {
		this.io.setPointerField(this, 27, u64vals);
		return this;
	}
	@Field(28) 
	public long i64max() {
		return this.io.getLongField(this, 28);
	}
	@Field(28) 
	public LIBMTP_allowed_values_struct i64max(long i64max) {
		this.io.setLongField(this, 28, i64max);
		return this;
	}
	@Field(29) 
	public long i64min() {
		return this.io.getLongField(this, 29);
	}
	@Field(29) 
	public LIBMTP_allowed_values_struct i64min(long i64min) {
		this.io.setLongField(this, 29, i64min);
		return this;
	}
	@Field(30) 
	public long i64step() {
		return this.io.getLongField(this, 30);
	}
	@Field(30) 
	public LIBMTP_allowed_values_struct i64step(long i64step) {
		this.io.setLongField(this, 30, i64step);
		return this;
	}
	/** C type : int64_t* */
	@Field(31) 
	public Pointer<Long > i64vals() {
		return this.io.getPointerField(this, 31);
	}
	/** C type : int64_t* */
	@Field(31) 
	public LIBMTP_allowed_values_struct i64vals(Pointer<Long > i64vals) {
		this.io.setPointerField(this, 31, i64vals);
		return this;
	}
	@Field(32) 
	public short num_entries() {
		return this.io.getShortField(this, 32);
	}
	@Field(32) 
	public LIBMTP_allowed_values_struct num_entries(short num_entries) {
		this.io.setShortField(this, 32, num_entries);
		return this;
	}
	/** C type : LIBMTP_datatype_t */
	@Field(33) 
	public IntValuedEnum<LIBMTP_datatype_t > datatype() {
		return this.io.getEnumField(this, 33);
	}
	/** C type : LIBMTP_datatype_t */
	@Field(33) 
	public LIBMTP_allowed_values_struct datatype(IntValuedEnum<LIBMTP_datatype_t > datatype) {
		this.io.setEnumField(this, 33, datatype);
		return this;
	}
	@Field(34) 
	public int is_range() {
		return this.io.getIntField(this, 34);
	}
	@Field(34) 
	public LIBMTP_allowed_values_struct is_range(int is_range) {
		this.io.setIntField(this, 34, is_range);
		return this;
	}
	public LIBMTP_allowed_values_struct() {
		super();
	}
	public LIBMTP_allowed_values_struct(Pointer pointer) {
		super(pointer);
	}
}
