package libmtp;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * A data structure to hold MTP device entries.<br>
 * <i>native declaration : /usr/local/Cellar/libmtp/1.1.13/include/libmtp.h:461</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mtp")
public class LIBMTP_device_entry_struct extends StructObject {
	static {
		BridJ.register();
	}
	/**
	 * < The vendor of this device<br>
	 * C type : char*
	 */
	@Field(0) 
	public Pointer<Byte > vendor() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * < The vendor of this device<br>
	 * C type : char*
	 */
	@Field(0) 
	public LIBMTP_device_entry_struct vendor(Pointer<Byte > vendor) {
		this.io.setPointerField(this, 0, vendor);
		return this;
	}
	/** < Vendor ID for this device */
	@Field(1) 
	public short vendor_id() {
		return this.io.getShortField(this, 1);
	}
	/** < Vendor ID for this device */
	@Field(1) 
	public LIBMTP_device_entry_struct vendor_id(short vendor_id) {
		this.io.setShortField(this, 1, vendor_id);
		return this;
	}
	/**
	 * < The product name of this device<br>
	 * C type : char*
	 */
	@Field(2) 
	public Pointer<Byte > product() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * < The product name of this device<br>
	 * C type : char*
	 */
	@Field(2) 
	public LIBMTP_device_entry_struct product(Pointer<Byte > product) {
		this.io.setPointerField(this, 2, product);
		return this;
	}
	/** < Product ID for this device */
	@Field(3) 
	public short product_id() {
		return this.io.getShortField(this, 3);
	}
	/** < Product ID for this device */
	@Field(3) 
	public LIBMTP_device_entry_struct product_id(short product_id) {
		this.io.setShortField(this, 3, product_id);
		return this;
	}
	/** < Bugs, device specifics etc */
	@Field(4) 
	public int device_flags() {
		return this.io.getIntField(this, 4);
	}
	/** < Bugs, device specifics etc */
	@Field(4) 
	public LIBMTP_device_entry_struct device_flags(int device_flags) {
		this.io.setIntField(this, 4, device_flags);
		return this;
	}
	public LIBMTP_device_entry_struct() {
		super();
	}
	public LIBMTP_device_entry_struct(Pointer pointer) {
		super(pointer);
	}
}
