package libmtp;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * MTP Playlist structure<br>
 * <i>native declaration : /usr/local/Cellar/libmtp/1.1.13/include/libmtp.h:666</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mtp")
public class LIBMTP_playlist_struct extends StructObject {
	static {
		BridJ.register();
	}
	/** < Unique playlist ID */
	@Field(0) 
	public int playlist_id() {
		return this.io.getIntField(this, 0);
	}
	/** < Unique playlist ID */
	@Field(0) 
	public LIBMTP_playlist_struct playlist_id(int playlist_id) {
		this.io.setIntField(this, 0, playlist_id);
		return this;
	}
	/** < ID of parent folder */
	@Field(1) 
	public int parent_id() {
		return this.io.getIntField(this, 1);
	}
	/** < ID of parent folder */
	@Field(1) 
	public LIBMTP_playlist_struct parent_id(int parent_id) {
		this.io.setIntField(this, 1, parent_id);
		return this;
	}
	/** < ID of storage holding this playlist */
	@Field(2) 
	public int storage_id() {
		return this.io.getIntField(this, 2);
	}
	/** < ID of storage holding this playlist */
	@Field(2) 
	public LIBMTP_playlist_struct storage_id(int storage_id) {
		this.io.setIntField(this, 2, storage_id);
		return this;
	}
	/**
	 * < Name of playlist<br>
	 * C type : char*
	 */
	@Field(3) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * < Name of playlist<br>
	 * C type : char*
	 */
	@Field(3) 
	public LIBMTP_playlist_struct name(Pointer<Byte > name) {
		this.io.setPointerField(this, 3, name);
		return this;
	}
	/**
	 * < The tracks in this playlist<br>
	 * C type : uint32_t*
	 */
	@Field(4) 
	public Pointer<Integer > tracks() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * < The tracks in this playlist<br>
	 * C type : uint32_t*
	 */
	@Field(4) 
	public LIBMTP_playlist_struct tracks(Pointer<Integer > tracks) {
		this.io.setPointerField(this, 4, tracks);
		return this;
	}
	/** < The number of tracks in this playlist */
	@Field(5) 
	public int no_tracks() {
		return this.io.getIntField(this, 5);
	}
	/** < The number of tracks in this playlist */
	@Field(5) 
	public LIBMTP_playlist_struct no_tracks(int no_tracks) {
		this.io.setIntField(this, 5, no_tracks);
		return this;
	}
	/**
	 * < Next playlist or NULL if last playlist<br>
	 * C type : LIBMTP_playlist_t*
	 */
	@Field(6) 
	public Pointer<LIBMTP_playlist_struct > next() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * < Next playlist or NULL if last playlist<br>
	 * C type : LIBMTP_playlist_t*
	 */
	@Field(6) 
	public LIBMTP_playlist_struct next(Pointer<LIBMTP_playlist_struct > next) {
		this.io.setPointerField(this, 6, next);
		return this;
	}
	public LIBMTP_playlist_struct() {
		super();
	}
	public LIBMTP_playlist_struct(Pointer pointer) {
		super(pointer);
	}
}
