package libmtp;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * LIBMTP Device Storage structure<br>
 * <i>native declaration : /usr/local/Cellar/libmtp/1.1.13/include/libmtp.h:719</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mtp")
public class LIBMTP_devicestorage_struct extends StructObject {
	static {
		BridJ.register();
	}
	/** < Unique ID for this storage */
	@Field(0) 
	public int id() {
		return this.io.getIntField(this, 0);
	}
	/** < Unique ID for this storage */
	@Field(0) 
	public LIBMTP_devicestorage_struct id(int id) {
		this.io.setIntField(this, 0, id);
		return this;
	}
	/** < Storage type */
	@Field(1) 
	public short StorageType() {
		return this.io.getShortField(this, 1);
	}
	/** < Storage type */
	@Field(1) 
	public LIBMTP_devicestorage_struct StorageType(short StorageType) {
		this.io.setShortField(this, 1, StorageType);
		return this;
	}
	/** < Filesystem type */
	@Field(2) 
	public short FilesystemType() {
		return this.io.getShortField(this, 2);
	}
	/** < Filesystem type */
	@Field(2) 
	public LIBMTP_devicestorage_struct FilesystemType(short FilesystemType) {
		this.io.setShortField(this, 2, FilesystemType);
		return this;
	}
	/** < Access capability */
	@Field(3) 
	public short AccessCapability() {
		return this.io.getShortField(this, 3);
	}
	/** < Access capability */
	@Field(3) 
	public LIBMTP_devicestorage_struct AccessCapability(short AccessCapability) {
		this.io.setShortField(this, 3, AccessCapability);
		return this;
	}
	/** < Maximum capability */
	@Field(4) 
	public long MaxCapacity() {
		return this.io.getLongField(this, 4);
	}
	/** < Maximum capability */
	@Field(4) 
	public LIBMTP_devicestorage_struct MaxCapacity(long MaxCapacity) {
		this.io.setLongField(this, 4, MaxCapacity);
		return this;
	}
	/** < Free space in bytes */
	@Field(5) 
	public long FreeSpaceInBytes() {
		return this.io.getLongField(this, 5);
	}
	/** < Free space in bytes */
	@Field(5) 
	public LIBMTP_devicestorage_struct FreeSpaceInBytes(long FreeSpaceInBytes) {
		this.io.setLongField(this, 5, FreeSpaceInBytes);
		return this;
	}
	/** < Free space in objects */
	@Field(6) 
	public long FreeSpaceInObjects() {
		return this.io.getLongField(this, 6);
	}
	/** < Free space in objects */
	@Field(6) 
	public LIBMTP_devicestorage_struct FreeSpaceInObjects(long FreeSpaceInObjects) {
		this.io.setLongField(this, 6, FreeSpaceInObjects);
		return this;
	}
	/**
	 * < A brief description of this storage<br>
	 * C type : char*
	 */
	@Field(7) 
	public Pointer<Byte > StorageDescription() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * < A brief description of this storage<br>
	 * C type : char*
	 */
	@Field(7) 
	public LIBMTP_devicestorage_struct StorageDescription(Pointer<Byte > StorageDescription) {
		this.io.setPointerField(this, 7, StorageDescription);
		return this;
	}
	/**
	 * < A volume identifier<br>
	 * C type : char*
	 */
	@Field(8) 
	public Pointer<Byte > VolumeIdentifier() {
		return this.io.getPointerField(this, 8);
	}
	/**
	 * < A volume identifier<br>
	 * C type : char*
	 */
	@Field(8) 
	public LIBMTP_devicestorage_struct VolumeIdentifier(Pointer<Byte > VolumeIdentifier) {
		this.io.setPointerField(this, 8, VolumeIdentifier);
		return this;
	}
	/**
	 * < Next storage, follow this link until NULL<br>
	 * C type : LIBMTP_devicestorage_t*
	 */
	@Field(9) 
	public Pointer<LIBMTP_devicestorage_struct > next() {
		return this.io.getPointerField(this, 9);
	}
	/**
	 * < Next storage, follow this link until NULL<br>
	 * C type : LIBMTP_devicestorage_t*
	 */
	@Field(9) 
	public LIBMTP_devicestorage_struct next(Pointer<LIBMTP_devicestorage_struct > next) {
		this.io.setPointerField(this, 9, next);
		return this;
	}
	/**
	 * < Previous storage<br>
	 * C type : LIBMTP_devicestorage_t*
	 */
	@Field(10) 
	public Pointer<LIBMTP_devicestorage_struct > prev() {
		return this.io.getPointerField(this, 10);
	}
	/**
	 * < Previous storage<br>
	 * C type : LIBMTP_devicestorage_t*
	 */
	@Field(10) 
	public LIBMTP_devicestorage_struct prev(Pointer<LIBMTP_devicestorage_struct > prev) {
		this.io.setPointerField(this, 10, prev);
		return this;
	}
	public LIBMTP_devicestorage_struct() {
		super();
	}
	public LIBMTP_devicestorage_struct(Pointer pointer) {
		super(pointer);
	}
}
