package libmtp;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * MTP device extension holder struct<br>
 * <i>native declaration : /usr/local/Cellar/libmtp/1.1.13/include/libmtp.h:541</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mtp")
public class LIBMTP_device_extension_struct extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : char* */
	@Field(0) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : char* */
	@Field(0) 
	public LIBMTP_device_extension_struct name(Pointer<Byte > name) {
		this.io.setPointerField(this, 0, name);
		return this;
	}
	@Field(1) 
	public int major() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public LIBMTP_device_extension_struct major(int major) {
		this.io.setIntField(this, 1, major);
		return this;
	}
	@Field(2) 
	public int minor() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public LIBMTP_device_extension_struct minor(int minor) {
		this.io.setIntField(this, 2, minor);
		return this;
	}
	/** C type : LIBMTP_device_extension_t* */
	@Field(3) 
	public Pointer<LIBMTP_device_extension_struct > next() {
		return this.io.getPointerField(this, 3);
	}
	/** C type : LIBMTP_device_extension_t* */
	@Field(3) 
	public LIBMTP_device_extension_struct next(Pointer<LIBMTP_device_extension_struct > next) {
		this.io.setPointerField(this, 3, next);
		return this;
	}
	public LIBMTP_device_extension_struct() {
		super();
	}
	public LIBMTP_device_extension_struct(Pointer pointer) {
		super(pointer);
	}
}
