package libmtp;
import libmtp.LibmtpLibrary.LIBMTP_filetype_t;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * LIBMTP Object RepresentativeSampleData Structure<br>
 * <i>native declaration : /usr/local/Cellar/libmtp/1.1.13/include/libmtp.h:707</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mtp")
public class LIBMTP_filesampledata_struct extends StructObject {
	static {
		BridJ.register();
	}
	/** < Width of sample if it is an image */
	@Field(0) 
	public int width() {
		return this.io.getIntField(this, 0);
	}
	/** < Width of sample if it is an image */
	@Field(0) 
	public LIBMTP_filesampledata_struct width(int width) {
		this.io.setIntField(this, 0, width);
		return this;
	}
	/** < Height of sample if it is an image */
	@Field(1) 
	public int height() {
		return this.io.getIntField(this, 1);
	}
	/** < Height of sample if it is an image */
	@Field(1) 
	public LIBMTP_filesampledata_struct height(int height) {
		this.io.setIntField(this, 1, height);
		return this;
	}
	/** < Duration in milliseconds if it is audio */
	@Field(2) 
	public int duration() {
		return this.io.getIntField(this, 2);
	}
	/** < Duration in milliseconds if it is audio */
	@Field(2) 
	public LIBMTP_filesampledata_struct duration(int duration) {
		this.io.setIntField(this, 2, duration);
		return this;
	}
	/**
	 * < Filetype used for the sample<br>
	 * C type : LIBMTP_filetype_t
	 */
	@Field(3) 
	public IntValuedEnum<LIBMTP_filetype_t > filetype() {
		return this.io.getEnumField(this, 3);
	}
	/**
	 * < Filetype used for the sample<br>
	 * C type : LIBMTP_filetype_t
	 */
	@Field(3) 
	public LIBMTP_filesampledata_struct filetype(IntValuedEnum<LIBMTP_filetype_t > filetype) {
		this.io.setEnumField(this, 3, filetype);
		return this;
	}
	/** < Size of sample data in bytes */
	@Field(4) 
	public long size() {
		return this.io.getLongField(this, 4);
	}
	/** < Size of sample data in bytes */
	@Field(4) 
	public LIBMTP_filesampledata_struct size(long size) {
		this.io.setLongField(this, 4, size);
		return this;
	}
	/**
	 * < Sample data<br>
	 * C type : char*
	 */
	@Field(5) 
	public Pointer<Byte > data() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * < Sample data<br>
	 * C type : char*
	 */
	@Field(5) 
	public LIBMTP_filesampledata_struct data(Pointer<Byte > data) {
		this.io.setPointerField(this, 5, data);
		return this;
	}
	public LIBMTP_filesampledata_struct() {
		super();
	}
	public LIBMTP_filesampledata_struct(Pointer pointer) {
		super(pointer);
	}
}
